using System;
using SpaceBlocks.Libs.Sdk.Models;
using <%= name %>.AutoGenerated.Api;
using <%= name %>.AutoGenerated.Client;

namespace <%= name %>
{
    public class <%= clientName %>
    {
        public <%= clientName %>(Uri basePath, AuthenticationOptions authenticationOptions, Uri? authUrl = null)
        {
            authUrl ??= new Uri("https://auth.spaceblocks.cloud");
            var configuration = new Configuration();
            var apiClient = new ApiClient(basePath, authUrl, authenticationOptions);
        }
    }
}
