name: Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
<% if(dotnet) { %>
      # .NET Tests
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          source-url: https://nuget.pkg.github.com/wemogy/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.WEMOGY_PACKAGES_TOKEN }}
      - name: Test .NET Solution
        working-directory: src
        shell: bash
        run: dotnet test -c Release /p:CollectCoverage=true -m:1
<% } %>
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.0.2
        with:
          filename: src/coverage.cobertura.xml
          badge: true
          format: 'markdown'
          output: 'both'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
        with:
          recreate: true
          path: code-coverage-results.md
<% if(helm) { %>
      # Helm Chart Tests
      - name: Validate Helm Chart
        working-directory: env/helm/<% helmName %>
        run: |
          helm dependency update
          helm lint
<% } %>
